apiVersion: sql.tanzu.vmware.com/v1
kind: Postgres
metadata:
  name: pg-instance-example
  namespace: vmware-poc
spec:
  memory: 2000Mi
  cpu: "2"
  storageClassName: standard 
  storageSize: 40000M
  pgConfig:
    dbname: pg-instance-example
    username: pgadmin
  serviceType: LoadBalancer
  highAvailability:
    enabled: true 
  logLevel: Debug
