apiVersion: v1
kind: Secret
metadata:
  name: s3-secret-example
type: generic
stringData:
  bucket: "postgresql-backups"
  region: "us-east-1"
  endpoint: "minio.minio.svc.cluster.local"
  key: "admin"
  keySecret: "adminsecret"
  #optional fields
  port: "9000"
  uriStyle: "path"
  verifyTLS: "true"
